language: scala

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - openjdk8

dist: trusty
sudo: true

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

after_success:
  - |
    if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
      echo "$PGP_SECRET" | base64 --decode | gpg --import
      if [ -z "$TRAVIS_TAG" ]; then
        echo "Publishing snapshot"
        sbt ++$TRAVIS_SCALA_VERSION publishSigned
      else
        echo "Publishing package"
        sbt ++$TRAVIS_SCALA_VERSION "sonatypeOpen xtract-$TRAVIS_TAG" publishSigned sonatypeReleaseAll
      fi
    fi

deploy:
  api_key: $GITHUB_AUTH
  file:
    - xtract-core/target/**/*.jar
    - testing/target/**/*.jar
  file_glob: true
  provider: releases
  skip_cleanup: true
  on:
    tags: true

before_script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'

before_cache:
  #Avoid unncessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
